name: Deactivate

on:
  pull_request:
    types: [ closed ]
    
jobs:
  deactivate:
    name: â˜  Deactivate
    runs-on: ubuntu-latest
    steps:
    - uses: SocialGouv/actions/autodevops-deactivate@v1
      with:
        kube-config: ${{ secrets.KUBECONFIG  }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
